# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJboz56fu_C2-qFIHsOacY14GBwJNRXE
"""

print ("Hello, world");